# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca900ee643a2511ed1707a8a1315fd30c9f56cada36be46ac8af58c7755c177a9e2be320f9a65de045f3f89f5c459d7edbcb3b9505ee0b3d3a5f1b66fe5ac89f

test:
  secret_key_base: 6c5b18993d1d9379968681b20143ee62dfb6c921260125a8c281f50d8c838a182ca96dab5218a03678b77dea80043940f5dc1343b6218e4b984a4b0444a8d006

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 6c5b18993d1d9379968681b20143ee62dfb6c921260125a8c281f50d8c838a182ca96dab5218a03678b77dea80043940f5dc1343b6218e4b984a4b0444a8d006
